### ISSUE TITLE
strjoin error

### ISSUE THREAD

**Issue by MariaGarciaEco** [add-my-pet/DEBtool_M#12]
Hi team,
 I am hoping you can guide me  in order to fix a result output issue.
When I run DEB tool for my pet or any other pets in the database I get this error:
 Error using strjoin
First input must be a string array or cell array of character vectors.

Error in matlab.net.URI/get.EncodedPath (line 514)
                str = strjoin(path, '/');

Error in matlab.net.URI/string (line 680)
                path = obj.EncodedPath;

Error in matlab.internal.web.WebCommandBrowserLauncher/get.LoadUrl (line 46)
                url = string(obj.Uri);

Error in web (line 112)
        location = launcher.LoadUrl;

Error in prt_results_my_pet (line 189)
    web(fileName,'-browser') % open html in systems browser

Error in results_pets (line 588)
      prt_results_my_pet(parPets, metaPar, txtPar, data, metaData, txtData, prdData);

Error in estim_pars (line 157)
    results_pets(par, metaPar, txtPar, data, auxData, metaData, txtData, weights);

Error in run_Odobenus_rosmarus_rosmarus (line 15)
estim_pars;
 
Your help would be much appreciated
thanks a million,
Maria 

Dr Maria Isabel Garcia Rojas
Postdoctoral Research Fellow
University of Winnipeg

**Comment by starraugustine** [comment]
Hi,
Did you use the latest version of DEBtool_M, and have you run the run file? 

I need a bit more information to help you. Alternative write to me at starrlight@tecnico.ulisboa.pt with in zip file the files you are using if having latest version of DEBtool_M .

**Comment by MariaGarciaEco** [comment]
Yes I used the last version of DEBTool_M and run the run file.
I tried multiple run files and my pet from the database.
As the error is a Matlab error I wonder if the issues is some code compatibility of the DEBTool_M with a newer version of Matlab? I have the latest Matlab R2022b

**Comment by MariaGarciaEco** [comment]
This is the strjoin file in my version  Matlab:

function joinedStr = strjoin(c, aDelim)
%STRJOIN  Join cell array of strings into single string
%   S = STRJOIN(C) constructs the string S by linking each string within
%   cell array of strings C together with a space.
%
%   S = STRJOIN(C, DELIMITER) constructs S by linking each element of C
%   with the elements of DELIMITER. DELIMITER can be either a string or a
%   cell array of strings having one fewer element than C.
%
%   If DELIMITER is a string, then STRJOIN forms S by inserting DELIMITER
%   between each element of C. DELIMITER can include any of these escape
%   sequences:
%       \\   Backslash
%       \0   Null
%       \a   Alarm
%       \b   Backspace
%       \f   Form feed
%       \n   New line
%       \r   Carriage return
%       \t   Horizontal tab
%       \v   Vertical tab
%
%   If DELIMITER is a cell array of strings, then STRJOIN forms S by
%   interleaving the elements of DELIMITER and C. In this case, all
%   characters in DELIMITER are inserted as literal text, and escape
%   characters are not supported.
%
%   Examples:
%
%       c = {'one', 'two', 'three'};
%
%       % Join with space.
%       strjoin(c)
%       % 'one two three'
%
%       % Join as a comma separated list.
%       strjoin(c, ', ')
%       % 'one, two, three'
%
%       % Join with a cell array of strings DELIMITER.
%       strjoin(c, {' + ', ' = '})
%       % 'one + two = three'
%
%   See also STRCAT, STRSPLIT.

%   Copyright 2012 The MathWorks, Inc.
%   $Revision: 1.1.6.2 $  $Date: 2012/11/15 13:56:49 $

narginchk(1, 2);

% Check input arguments.
if ~iscellstr(c)
    error(message('MATLAB:strjoin:InvalidCellType'));
end
if nargin < 2
    aDelim = ' ';
end

% Allocate a cell to join into - the first row will be C and the second, D.
numStrs = numel(c);
joinedCell = cell(2, numStrs);
joinedCell(1, :) = reshape(c, 1, numStrs);
if isstr(aDelim)
    if numStrs < 1
        joinedStr = '';
        return;
    end
    escapedDelim = strescape(aDelim);
    joinedCell(2, 1:numStrs-1) = {escapedDelim};
elseif isCellString(aDelim)
    numDelims = numel(aDelim);
    if numDelims ~= numStrs - 1
        error(message('MATLAB:strjoin:WrongNumberOfDelimiterElements'));
    end
    joinedCell(2, 1:numDelims) = aDelim(:);
else
    error(message('MATLAB:strjoin:InvalidDelimiterType'));
end

% Join.
joinedStr  = [joinedCell{:}];

end

**Comment by MariaGarciaEco** [comment]
Hi,

Thank you for your help. I have tried over 30 different species codes in myPet without modifying them and they all show the same error. So, I don't' think is my file but the compatibility between codes across DEBTool_M and my version of Matlab R2022b.
Perhaps we could Zoom so I can share my screen with you?
See main error and SRTJOIN code below

Error =
Error using strjoin
First input must be a string array or cell array of character vectors.

Error in matlab.net.URI/get.EncodedPath (line 514)
                str = strjoin(path, '/');

Error in matlab.net.URI/string (line 680)
                path = obj.EncodedPath;

Error in matlab.internal.web.WebCommandBrowserLauncher/get.LoadUrl (line 46)
                url = string(obj.Uri);

Error in web (line 112)
        location = launcher.LoadUrl;

Error in prt_results_my_pet (line 189)
    web(fileName,'-browser') % open html in systems browser

Error in results_pets (line 588)
      prt_results_my_pet(parPets, metaPar, txtPar, data, metaData, txtData, prdData);

Error in estim_pars (line 157)
    results_pets(par, metaPar, txtPar, data, auxData, metaData, txtData, weights);

Error in run_Odobenus_rosmarus_rosmarus (line 15)
estim_pars;


The MATLAB file that is creating the first error is as follows:


This is the strjoin file in my version Matlab:

function joinedStr = strjoin(c, aDelim)
%STRJOIN Join cell array of strings into single string
% S = STRJOIN(C) constructs the string S by linking each string within
% cell array of strings C together with a space.
%
% S = STRJOIN(C, DELIMITER) constructs S by linking each element of C
% with the elements of DELIMITER. DELIMITER can be either a string or a
% cell array of strings having one fewer element than C.
%
% If DELIMITER is a string, then STRJOIN forms S by inserting DELIMITER
% between each element of C. DELIMITER can include any of these escape
% sequences:
% \ Backslash
% \0 Null
% \a Alarm
% \b Backspace
% \f Form feed
% \n New line
% \r Carriage return
% \t Horizontal tab
% \v Vertical tab
%
% If DELIMITER is a cell array of strings, then STRJOIN forms S by
% interleaving the elements of DELIMITER and C. In this case, all
% characters in DELIMITER are inserted as literal text, and escape
% characters are not supported.
%
% Examples:
%
% c = {'one', 'two', 'three'};
%
% % Join with space.
% strjoin(c)
% % 'one two three'
%
% % Join as a comma separated list.
% strjoin(c, ', ')
% % 'one, two, three'
%
% % Join with a cell array of strings DELIMITER.
% strjoin(c, {' + ', ' = '})
% % 'one + two = three'
%
% See also STRCAT, STRSPLIT.

% Copyright 2012 The MathWorks, Inc.
% $Revision: 1.1.6.2 $ ����:2012/11/1513:56:49

narginchk(1, 2);

% Check input arguments.
if ~iscellstr(c)
error(message('MATLAB:strjoin:InvalidCellType'));
end
if nargin < 2
aDelim = ' ';
end

% Allocate a cell to join into - the first row will be C and the second, D.
numStrs = numel(c);
joinedCell = cell(2, numStrs);
joinedCell(1, :) = reshape(c, 1, numStrs);
if isstr(aDelim)
if numStrs < 1
joinedStr = '';
return;
end
escapedDelim = strescape(aDelim);
joinedCell(2, 1:numStrs-1) = {escapedDelim};
elseif isCellString(aDelim)
numDelims = numel(aDelim);
if numDelims ~= numStrs - 1
error(message('MATLAB:strjoin:WrongNumberOfDelimiterElements'));
end
joinedCell(2, 1:numDelims) = aDelim(:);
else
error(message('MATLAB:strjoin:InvalidDelimiterType'));
end

% Join.
joinedStr = [joinedCell{:}];

end

Looking forward to hearing from you

Cheers
Maria
________________________________

**Comment by starraugustine** [comment]
Hi,

I am in EU, so with some time difference and I went to sleep last night after our first exchange, so sorry for the delays. I am reading your message, and checking in the team who is using Matlab 2022 and will come back to you very soon.

**Comment by starraugustine** [comment]
Hi,

We have to study, and find the source of the problem. Meanwhile can you please change the results_output option from 3 to -3 see below: 

estim_options('results_output', -3); 

this will stop the html reporting, and I think will allow you to run the code and work. We stay in contact about the strjoin and versions, but let me know ASAP if change the output option also gives you a  problem

**Comment by joendijk** [comment]
Hi,

I'm running into the exact same issue, also with Matlab R2022b.

```
>> run_Mytilus_edulis
In mydata_Mytilus_edulis.m: The bibkey guess defined for Wwb has no corresponding reference in biblist. 
In mydata_Mytilus_edulis.m: The bibkey guess defined for Wwp has no corresponding reference in biblist. 
In mydata_Mytilus_edulis.m: The bibkey guess defined for Wwi has no corresponding reference in biblist. 
warning from get_pars: not all parameters in get_pars_6 are free
Error using strjoin
First input must be a string array or cell array of character vectors.

Error in matlab.net.URI/get.EncodedPath (line 514)
                str = strjoin(path, '/');

Error in matlab.net.URI/string (line 680)
                path = obj.EncodedPath;

Error in matlab.internal.web.WebCommandBrowserLauncher/get.LoadUrl (line 46)
                url = string(obj.Uri);

Error in web (line 112)
        location = launcher.LoadUrl;

Error in prt_results_my_pet (line 189)
    web(fileName,'-browser') % open html in systems browser

Error in results_pets (line 588)
      prt_results_my_pet(parPets, metaPar, txtPar, data, metaData, txtData, prdData);

Error in estim_pars (line 157)
    results_pets(par, metaPar, txtPar, data, auxData, metaData, txtData, weights);

Error in run_Mytilus_edulis (line 15)
estim_pars;
 
>> 
```
It still runs the DEB model it seems, producing graphs and png (results_output set to e.g. 3), but no .mat file is created.  Previous version R2021b did work correctly. My knowledge about Matlab coding is rather limited, so I guess the advice is to use the older Matlab version until the issue is solved.

Kind regards,
Jeroen

**Comment by starraugustine** [comment]
We found where this happens. Matlab made a change in 2022 we think is to its built in function "web" - in earlier version l 112 is a comment, but the complaint from Maria's report say "Error in web (line 112)
        location = launcher.LoadUrl;"
in the zip file you have the 2021A web.m function - can you put that in your local work directory where the run, etc files are and try and see if that problem is solved?
[web.zip](https://github.com/add-my-pet/DEBtool_M/files/11048426/web.zip)

**Comment by joendijk** [comment]
Hi,

That indeed resolves the errors and now html output and the results .mat file are produced. Many thanks!

Kind regards,
Jeroen

**Comment by MariaGarciaEco** [comment]
Thank you so much for looking into it.
I look forward to hearing from you

Cheers
Maria
________________________________

**Comment by MariaGarciaEco** [comment]
It worked :) Thank you so much for your help
