### ISSUE TITLE
DEB function strjoin.m overlaps MATLAB default strjoin.m function

### ISSUE THREAD

**Issue by tongyaopu** [add-my-pet/DEBtool_M#13]
MATLAB native strjoin.m function is needed for opening web browsers and MATLAB documentation. See:
https://www.mathworks.com/matlabcentral/answers/1712625-doc-command-doesn-t-work

I suggest renaming the DEB lib/misc/strjoin.m

**Comment by starraugustine** [comment]
DEB lib/misc/strjoin.m has been deleted. Please sync or download DEBtool_M again. Thank you for bringing this to our attention. I think that the presence of strjoin in that folder was a relic work around for some matlab error some users were getting. We hope that there is still compatibility with older matlab versions.
