### ISSUE TITLE
What is the unit for variables in get_pars_u() function?

### ISSUE THREAD

**Issue by tongyaopu** [add-my-pet/DEBtool_M#14]
The documentation of `get_pars_u()` suggests its inputs and outputs have units in terms of `mmol` and `mm`. However, I did not see any conversions to the default `mol` and `cm` when other functions call it (e.g. `mydata_flux()`).

**Comment by starraugustine** [comment]
Thank you! I have changed the units from mmol to mol and mm to cm in the description. It is pushed to GitHub.
